# Numpy Quickstart Guide (http://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [1]:
'''
NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all 
of the same type, indexed by a tuple of positive integers. In Numpy dimensions are called axes. The number of axes is 
'rank'. For example, the coordinates of a point in 3D space [1, 2, 1] is an array of rank 1, because it has one axis. 
That axis has a length of 3. In the example pictured below, the array has rank 2 (it is 2-dimensional). The first 
dimension (axis) has a length of 2, the second dimension has a length of 3.
'''
[[ 1., 0., 0.],
 [ 0., 1., 2.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 2.0]]

In [19]:
from __future__ import print_function, unicode_literals, division
import numpy as np
%matplotlib inline 
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [20]:
'''
The dimensions of the array: this is a tuple of integers indicating the size of the array in each dimension. For a 
matrix with n rows and m columns, shape will be (n,m). The length of the shape tuple is therefore the rank, or 
number of dimensions, ndim.
'''
a.shape

(3, 5)

In [21]:
# the number of axes (dimensions) of the array. In the Python world, the number of dimensions is referred to as rank.
a.ndim

2

In [22]:
a.dtype.name

'int64'

In [23]:
'''
The size in bytes of each element of the array. For example, an array of elements of type float64 has itemsize 8
(=64/8), while one of type complex32 has itemsize 4 (=32/8). It is equivalent to ndarray.dtype.itemsize.
'''
a.itemsize

8

In [24]:
# the total number of elements of the array. This is equal to the product of the elements of shape.
a.size

15

In [25]:
type(a)

numpy.ndarray

In [26]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [27]:
type(b)

numpy.ndarray

In [29]:
'''
ARRAY CREATION: There are several ways to create arrays. For example, you can create an array from a regular Python 
list or tuple using the array function. The type of the resulting array is deduced from the type of the elements in 
the sequences.
'''
import numpy as np
a = np.array([2,3,4])
print('a:', a)
print('a.dtype:', a.dtype)
b = np.array([1.2, 3.5, 5.1])
print('b.dtype:', b.dtype)
'''
A frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of 
numbers as an argument.
a = np.array(1,2,3,4)    # WRONG
a = np.array([1,2,3,4])  # RIGHT
'''

a: [2 3 4]
a.dtype: int64
b.dtype: float64


u'\nA frequent error consists in calling array with multiple numeric arguments, rather than providing a single list of \nnumbers as an argument.\na = np.array(1,2,3,4)    # WRONG\na = np.array([1,2,3,4])  # RIGHT\n'

In [30]:
'''
'array' transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into 
three-dimensional arrays, and so on.
'''
b = np.array([(1.5,2,3), (4,5,6)])
print('b: ', b)

# The type of the array can also be explicitly specified at creation time:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
print('c: ', c)


b:  [[ 1.5  2.   3. ]
 [ 4.   5.   6. ]]
c:  [[ 1.+0.j  2.+0.j]
 [ 3.+0.j  4.+0.j]]


In [31]:
'''
Often, the elements of an array are originally unknown, but its size is known. Hence, NumPy offers several functions
to create arrays with initial placeholder content. These minimize the necessity of growing arrays, an expensive 
operation.

The function 'zeros' creates an array full of zeros, the function 'ones' creates an array full of ones, and the 
function 'empty' creates an array whose initial content is random and depends on the state of the memory. 
By default, the dtype of the created array is float64.
'''
print(np.zeros( (3,4) ))
print()
print(np.ones( (2,3,4), dtype=np.int16 ))                # dtype can also be specified
print(np.empty( (2,3) ))                                 # uninitialized, output may vary

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
[[  1.39069238e-309   1.39069238e-309   1.39069238e-309]
 [  1.39069238e-309   1.39069238e-309   1.39069238e-309]]


In [32]:
# To create sequences of numbers, NumPy provides a function analogous to 'range' that returns arrays instead of lists
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [33]:
np.arange( 0, 2, 0.3 )                 # it accepts float arguments

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [34]:
'''
When arange is used with floating point arguments, it is generally not possible to predict the number of elements 
obtained, due to the finite floating point precision. For this reason, it is usually better to use the function 
linspace that receives as an argument the number of elements that we want, instead of the step:
'''
from numpy import pi
print(np.linspace( 0, 2, 9 ))                 # 9 numbers from 0 to 2
x = np.linspace( 0, 2*pi, 100 )        # useful to evaluate function at lots of points
f = np.sin(x)
print('x: ',x)
print('f: ',f)

[ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]
x:  [ 0.          0.06346652  0.12693304  0.19039955  0.25386607  0.31733259
  0.38079911  0.44426563  0.50773215  0.57119866  0.63466518  0.6981317
  0.76159822  0.82506474  0.88853126  0.95199777  1.01546429  1.07893081
  1.14239733  1.20586385  1.26933037  1.33279688  1.3962634   1.45972992
  1.52319644  1.58666296  1.65012947  1.71359599  1.77706251  1.84052903
  1.90399555  1.96746207  2.03092858  2.0943951   2.15786162  2.22132814
  2.28479466  2.34826118  2.41172769  2.47519421  2.53866073  2.60212725
  2.66559377  2.72906028  2.7925268   2.85599332  2.91945984  2.98292636
  3.04639288  3.10985939  3.17332591  3.23679243  3.30025895  3.36372547
  3.42719199  3.4906585   3.55412502  3.61759154  3.68105806  3.74452458
  3.8079911   3.87145761  3.93492413  3.99839065  4.06185717  4.12532369
  4.1887902   4.25225672  4.31572324  4.37918976  4.44265628  4.5061228
  4.56958931  4.63305583  4.69652235  4.75998887  4.82345539  4.88

In [35]:
'''
Printing Arrays -- I've already done some of this above:

When you print an array, NumPy displays it in a similar way to nested lists, but with the following layout:

. the last axis is printed from left to right,
. the second-to-last is printed from top to bottom,
. the rest are also printed from top to bottom, with each slice separated from the next by an empty line.
. One-dimensional arrays are then printed as rows, bidimensionals as matrices and tridimensionals as lists of matrices.
'''
a = np.arange(6)                         # 1d array
print(a)
print()
b = np.arange(12).reshape(4,3)           # 2d array
print(b)
print()
c = np.arange(24).reshape(2,3,4)         # 3d array
print(c)


[0 1 2 3 4 5]

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [36]:
'''
If an array is too large to be printed, NumPy automatically skips the central part of the array and only prints the 
corners:
'''
print(np.arange(10000))
print()
print(np.arange(10000).reshape(100,100))
print()
'''
To disable this behaviour and force NumPy to print the entire array, you can change the printing options using 
set_printoptions.
'''
np.set_printoptions(threshold='nan')

[   0    1    2 ..., 9997 9998 9999]

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]



In [37]:
'''
Basic Operations:
Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.
'''
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
print('a: ',a)
print('b: ',b)
c = a-b
print('c: ',c)
print('b**2: ', b**2)
print('10*np.sin(a): ', 10*np.sin(a))
print('a<35: ', a<35)


a:  [20 30 40 50]
b:  [0 1 2 3]
c:  [20 29 38 47]
b**2:  [0 1 4 9]
10*np.sin(a):  [ 9.12945251 -9.88031624  7.4511316  -2.62374854]
a<35:  [ True  True False False]


In [39]:
'''
Unlike in many matrix languages, the product operator '*' operates elementwise in NumPy arrays. The matrix product can 
be performed using the dot function or method:
'''
A = np.array( [[1,1], [0,1]] )
B = np.array( [[2,0],[3,4]] )
print('A: ',A)
print('B: ',B)
print('A*B: ',A*B)                         # elementwise product
print('A.dot(B): ',A.dot(B))                    # matrix product
print('np.dot(A,B): ',np.dot(A, B))                # another matrix product


A:  [[1 1]
 [0 1]]
B:  [[2 0]
 [3 4]]
A*B:  [[2 0]
 [0 4]]
A.dot(B):  [[5 4]
 [3 4]]
np.dot(A,B):  [[5 4]
 [3 4]]


In [40]:
# Some operations, such as += and *=, act in place to modify an existing array rather than create a new one
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))
a *= 3
print('a: ', a)
b += a
print('b: ', b)
a += b                  # b is not automatically converted to integer type

a:  [[3 3 3]
 [3 3 3]]
b:  [[ 3.83517091  3.5857252   3.36490547]
 [ 3.47692644  3.47002398  3.61909118]]


TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [41]:
'''
When operating with arrays of different types, the type of the resulting array corresponds to the more general or 
precise one (a behavior known as upcasting).
'''
a = np.ones(3, dtype=np.int32)
b = np.linspace(0,pi,3)
print('b.dtype.name: ', b.dtype.name)
c = a+b
print('c: ', c)
print('c.dtype.name: ', c.dtype.name)
d = np.exp(c*1j)
print('d: ', d)
print('d.dtype.name: ', d.dtype.name)

b.dtype.name:  float64
c:  [ 1.          2.57079633  4.14159265]
c.dtype.name:  float64
d:  [ 0.54030231+0.84147098j -0.84147098+0.54030231j -0.54030231-0.84147098j]
d.dtype.name:  complex128


In [42]:
'''
Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the 
ndarray class.
'''
a = np.random.random((2,3))
print('a: ', a)
print('a.sum(): ', a.sum())
print('a.min(): ', a.min())
print('a.max(): ', a.max())

a:  [[ 0.70079728  0.38044637  0.41714954]
 [ 0.3808567   0.08807236  0.06263758]]
a.sum():  2.02995983346
a.min():  0.0626375797158
a.max():  0.700797276612


In [43]:
'''
By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. 
However, by specifying the axis parameter you can apply an operation along the specified axis of an array:
'''
b = np.arange(12).reshape(3,4)
print('b: ', b)
print('b.sum(axis=0): ', b.sum(axis=0))  # sum of each column
print('b.min(axis=1): ', b.min(axis=1))  # min of each row
print('b.cumsum(axis=1): ', b.cumsum(axis=1))  # cumulative sum along each row

b:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b.sum(axis=0):  [12 15 18 21]
b.min(axis=1):  [0 4 8]
b.cumsum(axis=1):  [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [44]:
'''
Universal Functions:

NumPy provides familiar mathematical functions such as sin, cos, and exp. In NumPy, these are called “universal 
functions”(ufunc). Within NumPy, these functions operate elementwise on an array, producing an array as output.
'''
B = np.arange(3)
print('B: ', B)
print('np.exp(B): ', np.exp(B))
C = np.array([2., -1., 4.])
print('C: ', C)
print('np.add(B, C): ', np.add(B, C))

B:  [0 1 2]
np.exp(B):  [ 1.          2.71828183  7.3890561 ]
C:  [ 2. -1.  4.]
np.add(B, C):  [ 2.  0.  6.]


In [45]:
'''
Indexing, Slicing and Iterating:

One-dimensional arrays can be indexed, sliced and iterated over, much like lists and other Python sequences.
'''
a = np.arange(10)**3
print('a: ', a)
print('a[2]: ', a[2])
print('a[2:5]: ', a[2:5])
a[:6:2] = -1000    # equivalent to a[0:6:2] = -1000; from start to position 6, exclusive, set every 2nd element to 
                   # -1000
print('a: ', a)
print('a[ : :-1]: ', a[ : :-1])                                 # reversed a

for i in a:
    print(i**(1/3.))

a:  [  0   1   8  27  64 125 216 343 512 729]
a[2]:  8
a[2:5]:  [ 8 27 64]
a:  [-1000     1 -1000    27 -1000   125   216   343   512   729]
a[ : :-1]:  [  729   512   343   216   125 -1000    27 -1000     1 -1000]
nan
1.0
nan
3.0
nan
5.0
6.0
7.0
8.0
9.0


/Users/markyashar/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py:16: RuntimeWarning: invalid value encountered in power


In [46]:
# Multidimensional arrays can have one index per axis. These indices are given in a tuple separated by commas:

def f(x,y):
    return 10*x+y

b = np.fromfunction(f,(5,4),dtype=int)
print('b: ', b)
print('b[2,3]: ', b[2,3])
print('b[0:5, 1]: ', b[0:5, 1])                       # each row in the second column of b
print('b[ : ,1]: ', b[ : ,1])                        # equivalent to the previous example
print('b[1:3, : ]: ', b[1:3, :])                      # each column in the second and third row of b

# When fewer indices are provided than the number of axes, the missing indices are considered complete slices:
print('b[-1]: ', b[-1])                                  # the last row. Equivalent to b[-1,:]

b:  [[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
b[2,3]:  23
b[0:5, 1]:  [ 1 11 21 31 41]
b[ : ,1]:  [ 1 11 21 31 41]
b[1:3, : ]:  [[10 11 12 13]
 [20 21 22 23]]
b[-1]:  [40 41 42 43]


In [48]:
'''
The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent 
the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is a rank 5 
array (i.e., it has 5 axes), then

x[1,2,...] is equivalent to x[1,2,:,:,:],

x[...,3] to x[:,:,:,:,3] and

x[4,...,5,:] to x[4,:,:,5,:].
'''

c = np.array( [[[  0,  1,  2], [10,12,13]],               # a 3D array (two stacked 2D arrays)
               [[100,101,102],
                 [110,112,113]]])
print('c.shape: ', c.shape)
print('c[1,...]: ', c[1,...])                                   # same as c[1,:,:] or c[1]
print('c[...,2]: ', c[...,2])                                   # same as c[:,:,2]


c.shape:  (2, 2, 3)
c[1,...]:  [[100 101 102]
 [110 112 113]]
c[...,2]:  [[  2  13]
 [102 113]]


In [49]:
# Iterating over multidimensional arrays is done with respect to the first axis:
for row in b:
    print(row)

[0 1 2 3]
[10 11 12 13]
[20 21 22 23]
[30 31 32 33]
[40 41 42 43]


In [50]:
# However, if one wants to perform an operation on each element in the array, one can use the 'flat' attribute which 
# is an iterator over all the elements of the array:
for element in b.flat:
    print(element)

0
1
2
3
10
11
12
13
20
21
22
23
30
31
32
33
40
41
42
43


In [51]:
'''
Shape Manipulation
Changing the shape of an array

An array has a shape given by the number of elements along each axis:
'''
a = np.floor(10*np.random.random((3,4)))
print('a: ', a)
print('a.shape: ', a.shape)

# The shape of an array can be changed with various commands:
print('a.ravel(): ', a.ravel())   # flatten the array
a.shape = (6, 2)
print('a.T: ', a.T)


a:  [[ 0.  3.  8.  6.]
 [ 7.  8.  3.  5.]
 [ 4.  9.  1.  9.]]
a.shape:  (3, 4)
a.ravel():  [ 0.  3.  8.  6.  7.  8.  3.  5.  4.  9.  1.  9.]
a.T:  [[ 0.  8.  7.  3.  4.  1.]
 [ 3.  6.  8.  5.  9.  9.]]


In [52]:
'''
The order of the elements in the array resulting from ravel() is normally “C-style”, that is, the rightmost index 
“changes the fastest”, so the element after a[0,0] is a[0,1]. If the array is reshaped to some other shape, again the 
array is treated as “C-style”. Numpy normally creates arrays stored in this order, so ravel() will usually not need 
to copy its argument, but if the array was made by taking slices of another array or created with unusual options, it 
may need to be copied. The functions ravel() and reshape() can also be instructed, using an optional argument, to use 
FORTRAN-style arrays, in which the leftmost index changes the fastest.

The reshape function returns its argument with a modified shape, whereas the ndarray.resize method modifies the array 
itself:
'''
print('a: ',a)
a.resize((2,6))
print('a: ', a)

# If a dimension is given as -1 in a reshaping operation, the other dimensions are automatically calculated:
print('a.reshape(3,-1)', a.reshape(3,-1))

a:  [[ 0.  3.]
 [ 8.  6.]
 [ 7.  8.]
 [ 3.  5.]
 [ 4.  9.]
 [ 1.  9.]]
a:  [[ 0.  3.  8.  6.  7.  8.]
 [ 3.  5.  4.  9.  1.  9.]]
a.reshape(3,-1) [[ 0.  3.  8.  6.]
 [ 7.  8.  3.  5.]
 [ 4.  9.  1.  9.]]
